### ISSUE TITLE
INTERACTIVIDA_RA

### ISSUE THREAD

**Issue by ElvisS10** [SistemasTecTlaxiaco/diseno-de-interactividad-de-la-realidad-aumentada-equipo-josue#1]
[Interactividad objeto 3d.pdf](https://github.com/SistemasTecTlaxiaco/diseno-de-interactividad-de-la-realidad-aumentada-equipo-josue/files/6386579/Interactividad.objeto.3d.pdf)

**Comment by AxayacatlS** [comment]
Calificación 20

**Comment by josealfredo79** [comment]
esta bien hecho y revisado
